# Generated by Django 5.1.5 on 2025-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
