# Generated by Django 5.1.5 on 2025-01-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
