# Generated by Django 5.1.5 on 2025-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_alter_addresses_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
