# Generated by Django 5.1.5 on 2025-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_alter_addresses_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='city',
            field=models.CharField(default='Bangalore', max_length=200),
            preserve_default=False,
        ),
    ]
