# Generated by Django 5.1.5 on 2025-02-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_addresses_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='Landmark',
            new_name='landmark',
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
