# Generated by Django 5.1.5 on 2025-02-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0015_rename_landmark_addresses_landmark_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_item',
            new_name='Cart_items',
        ),
    ]
