# Generated by Django 5.1.5 on 2025-02-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_rename_cart_item_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
