# Generated by Django 5.1.5 on 2025-03-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0018_alter_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='quantity',
        ),
    ]
