# Generated by Django 5.1.5 on 2025-03-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_remove_cart_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
