# Generated by Django 5.1.5 on 2025-03-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0020_cart_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='addresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.addresses'),
        ),
    ]
