# Generated by Django 5.1.5 on 2025-03-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0027_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
