# Generated by Django 5.1.5 on 2025-04-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0032_order_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='user',
        ),
    ]
