# Generated by Django 5.1.5 on 2025-04-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0037_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
